# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|hosted_docs| "https://github.com/#{hosted_docs}" }

gem "asciidoctor"
gem "asciidoctor-diagram"
gem "asciidoctor-pdf"
gem "pygments.rb"
gem "mysql2"
gem "pg"
gem "sinatra"
